# Numpy exercises


## Exercise 1 - Element-wise addition of 2 numpy arrays
Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

In [2]:
import numpy as np

a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(2,3)
c = a + b
print(c)

[[ 0  2  4]
 [ 6  8 10]]


## Exercise 2 - Multiplying a matrix (numpy array) by a scalar
Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?EXERCISE 2 - Multiplying a matrix (numpy array) by a scalar

In [6]:
d = a * 2
print(d)

[[ 0  2  4]
 [ 6  8 10]]


##Exercise 3 - Array re-dimensioning
Convert a 1-D array to a 3-D array

In [8]:
a = np.arange(27)

b = a.reshape((3,3,3))

print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


##Exercise 4 - Array datatype conversion
Convert all the elements of a numpy array from float to integer datatype

In [10]:
a = np.array([1.1, 2.2, 3.3])
b = a.astype(int)
print(b)

[1 2 3]


## Exercise 5 - Custom Sequence Generation
Generate a sequence of numbers :

    [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34 36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70 72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]

In [12]:
a = np.arange(0, 101, 2) # 가운데 숫자는 index
print(a)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


## Exercise 6 - Getting the positions (indexes) where elements of 2 numpy arrays match
From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

In [14]:
a = np.array([0, 1, 2, 3, 4, 5, 77])
b = np.array([5, 4, 3, 2, 1, 0, 77])
print(np.where(a == b))

(array([6]),)
